### ISSUE TITLE
Running the contributed command:'picgo.uploadImageFromClipboard' failed.

### ISSUE THREAD

**Issue by tsunamilx** [PicGo/vs-picgo#11]
从剪贴板上传报错，有无配置项都报错。

配置项：
![image](https://user-images.githubusercontent.com/6290337/54344581-26a8da80-467c-11e9-875c-746d15865643.png)

报错日志：
[2019-03-14 17:04:02.647] [exthost] [info] ExtensionService#_doActivateExtension Spades.vs-picgo {"startup":false,"activationEvent":"onCommand:picgo.uploadImageFromClipboard"}
[2019-03-14 17:04:02.647] [exthost] [info] ExtensionService#loadCommonJSModule /Users/lixiao/.vscode/extensions/spades.vs-picgo-1.0.5/out/extension
[2019-03-14 17:04:03.897] [exthost] [error] TypeError: Cannot read property 'silent' of undefined
	at Logger.handleLog (/Users/lixiao/.vscode/extensions/spades.vs-picgo-1.0.5/node_modules/picgo/dist/lib/Logger.js:18:30)
	at Logger.error (/Users/lixiao/.vscode/extensions/spades.vs-picgo-1.0.5/node_modules/picgo/dist/lib/Logger.js:35:21)
	at PicGo.init (/Users/lixiao/.vscode/extensions/spades.vs-picgo-1.0.5/node_modules/picgo/dist/core/PicGo.js:62:22)
	at new PicGo (/Users/lixiao/.vscode/extensions/spades.vs-picgo-1.0.5/node_modules/picgo/dist/core/PicGo.js:36:14)
	at upload (/Users/lixiao/.vscode/extensions/spades.vs-picgo-1.0.5/out/extension.js:97:19)
	at uploadImageFromClipboard (/Users/lixiao/.vscode/extensions/spades.vs-picgo-1.0.5/out/extension.js:18:21)
	at vscode.commands.registerCommand (/Users/lixiao/.vscode/extensions/spades.vs-picgo-1.0.5/out/extension.js:147:81)
	at d._executeContributedCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:457:160)
	at d.$executeContributedCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:457:534)
	at h._doInvokeHandler (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:593:118)
	at h._invokeHandler (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:592:777)
	at h._receiveRequest (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:591:436)
	at h._receiveOneMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:590:279)
	at define.constructor._protocol.onMessage.e (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:588:565)
	at u.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:43:254)
	at e (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:39:64)
	at u.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:43:254)
	at s (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:168:754)
	at Socket.define.constructor._socketDataListener.e (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:168:960)
	at Socket.emit (events.js:182:13)
	at addChunk (_stream_readable.js:279:12)
	at readableAddChunk (_stream_readable.js:264:11)
	at Socket.Readable.push (_stream_readable.js:219:10)
	at Pipe.onread (net.js:636:20) picgo.uploadImageFromClipboard

**Comment by Spades-S** [comment]
@tsunamilx  配置文件里的 picgo.path 是指外部配置文件路径，当setting.json文件中有picgo.path会优先使用 这个路径下的文件作为配置文件，当不存在picgo.path时才会用 picBed里的配置信息。

文档里这里没写清楚，我找个时间更新一下

**Comment by tsunamilx** [comment]
发现跟 #5 是同一个问题，并没有修复。

**Comment by Spades-S** [comment]
@tsunamilx [Picgo-Core已修复](https://github.com/PicGo/PicGo-Core/issues/6#issuecomment-474237711)，插件已更新

**Comment by upupming** [comment]
v2.0.0 is coming and we should close this issue, please feel free to open another issue if the error remains.

Nightly build v2.0.0 is available at https://ci.appveyor.com/project/upupming/vs-picgo/build/artifacts, any feedback is welcome!

**Comment by ChaoXu1997** [comment]
使用v2.1.0版本时，遇到了相同的报错：Running the contributed command: 'picgo.uploadImageFromClipboard' failed.
