### ISSUE TITLE
[issue]Vscode中无法上传图片

### ISSUE THREAD

**Issue by maozuxiao** [PicGo/vs-picgo#110]
抱歉，又一次提错了位置……

### Describe the bug

[issue]Vscode中无法上传图片

### To Reproduce
<html>
<body>
<ol dir="auto" style="box-sizing: border-box; padding-left: 2em; margin-top: 0px; margin-bottom: 16px; color: rgb(201, 209, 217); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(13, 17, 23); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><li style="box-sizing: border-box; margin-left: 0px;">Vscode中安装PicGo插件</li><li style="box-sizing: border-box; margin-top: 0.25em; margin-left: 0px;">在PicGo中配置图床参数</li><li style="box-sizing: border-box; margin-top: 0.25em; margin-left: 0px;">使用如下命令测试但是提示错误</li></ol>

OS | Uploading an image from clipboard | Uploading images from explorer | Uploading an image from input box
-- | -- | -- | --
Windows/Unix | Ctrl + Alt + U | Ctrl + Alt + E | Ctrl + Alt + O
报错提示 | command 'picgo.uploadImageFromClipboard' not found | command 'picgo.uploadImageFromExplorer' not found | command 'picgo.uploadImageFromInputBox' not found | 

PS: 配置见下图
![image](https://user-images.githubusercontent.com/48650555/143817633-f9c254ba-6643-4b7f-be40-a79658b8ae7f.png)

### Expected behavior

可以正常上传图片

### Screenshots

![image](https://user-images.githubusercontent.com/48650555/143816847-38ce4aac-c541-437f-ae8e-78f9db3ee3d9.png)

### System information

- OS: Windows
- Version Windows 10

### VSCode information

- `Help` -> `About` -> `Copy`

  ```txt
 版本: 1.62.3 (user setup)
提交: ccbaa2d27e38e5afa3e5c21c1c7bef4657064247
日期: 2021-11-17T08:11:14.551Z
Electron: 13.5.2
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19042
  ```

- `vs-picgo` version

- Settings begin with `picgo`:v2.1.6

### Additional context

**Is this bug picBed specific, i.e. only the picBed you use is affected?** Yes/No.

**Is there any error in the console (`Help` -> `Toggle Developer tools`)?**: Yes/No.

```txt
If yes, please paste the error here.
```

**Comment by upupming** [comment]
@maozuxiao 请按照模板贴一下命令行报错信息的

**Comment by maozuxiao** [comment]
> @maozuxiao 请按照模板贴一下命令行报错信息的

你好看下是不是下面这一段
```text
[2021-11-29 16:46:19.676] [exthost] [error] Activating extension Spades.vs-picgo failed due to an error:
[2021-11-29 16:46:19.676] [exthost] [error] SyntaxError: Malformed JSON in file: C:\Users\MAO19/.picgo/config.json
Unexpected end of JSON input
	at unexpected_end (c:\Users\MAO19\.vscode\extensions\spades.vs-picgo-2.1.6\dist\extension.js:25961:17)
	at type (c:\Users\MAO19\.vscode\extensions\spades.vs-picgo-2.1.6\dist\extension.js:25987:5)
	at is (c:\Users\MAO19\.vscode\extensions\spades.vs-picgo-2.1.6\dist\extension.js:25995:17)
	at parse_object (c:\Users\MAO19\.vscode\extensions\spades.vs-picgo-2.1.6\dist\extension.js:26080:11)
	at walk (c:\Users\MAO19\.vscode\extensions\spades.vs-picgo-2.1.6\dist\extension.js:26178:12)
	at FileSync.parse [as deserialize] (c:\Users\MAO19\.vscode\extensions\spades.vs-picgo-2.1.6\dist\extension.js:26230:16)
	at FileSync.read (c:\Users\MAO19\.vscode\extensions\spades.vs-picgo-2.1.6\dist\extension.js:94448:30)
	at LodashWrapper.db.read (c:\Users\MAO19\.vscode\extensions\spades.vs-picgo-2.1.6\dist\extension.js:94523:21)
	at Object.module.exports [as default] (c:\Users\MAO19\.vscode\extensions\spades.vs-picgo-2.1.6\dist\extension.js:94542:13)
	at new DB (c:\Users\MAO19\.vscode\extensions\spades.vs-picgo-2.1.6\dist\extension.js:106155:34)
	at PicGo.initConfig (c:\Users\MAO19\.vscode\extensions\spades.vs-picgo-2.1.6\dist\extension.js:103330:19)
	at new PicGo (c:\Users\MAO19\.vscode\extensions\spades.vs-picgo-2.1.6\dist\extension.js:103309:14)
	at Object.51683 (c:\Users\MAO19\.vscode\extensions\spades.vs-picgo-2.1.6\dist\extension.js:170332:17)
	at __webpack_require__ (c:\Users\MAO19\.vscode\extensions\spades.vs-picgo-2.1.6\dist\extension.js:184620:42)
	at Object.50112 (c:\Users\MAO19\.vscode\extensions\spades.vs-picgo-2.1.6\dist\extension.js:169847:36)
	at __webpack_require__ (c:\Users\MAO19\.vscode\extensions\spades.vs-picgo-2.1.6\dist\extension.js:184620:42)
	at c:\Users\MAO19\.vscode\extensions\spades.vs-picgo-2.1.6\dist\extension.js:184674:18
	at Object.<anonymous> (c:\Users\MAO19\.vscode\extensions\spades.vs-picgo-2.1.6\dist\extension.js:184675:12)
```

**Comment by maozuxiao** [comment]
> > @maozuxiao 请按照模板贴一下命令行报错信息的
> 
> 你好看下是不是下面这一段
> 
> ```
> [2021-11-29 16:46:19.676] [exthost] [error] Activating extension Spades.vs-picgo failed due to an error:
> [2021-11-29 16:46:19.676] [exthost] [error] SyntaxError: Malformed JSON in file: C:\Users\MAO19/.picgo/config.json
> Unexpected end of JSON input
> 	at unexpected_end (c:\Users\MAO19\.vscode\extensions\spades.vs-picgo-2.1.6\dist\extension.js:25961:17)
> 	at type (c:\Users\MAO19\.vscode\extensions\spades.vs-picgo-2.1.6\dist\extension.js:25987:5)
> 	at is (c:\Users\MAO19\.vscode\extensions\spades.vs-picgo-2.1.6\dist\extension.js:25995:17)
> 	at parse_object (c:\Users\MAO19\.vscode\extensions\spades.vs-picgo-2.1.6\dist\extension.js:26080:11)
> 	at walk (c:\Users\MAO19\.vscode\extensions\spades.vs-picgo-2.1.6\dist\extension.js:26178:12)
> 	at FileSync.parse [as deserialize] (c:\Users\MAO19\.vscode\extensions\spades.vs-picgo-2.1.6\dist\extension.js:26230:16)
> 	at FileSync.read (c:\Users\MAO19\.vscode\extensions\spades.vs-picgo-2.1.6\dist\extension.js:94448:30)
> 	at LodashWrapper.db.read (c:\Users\MAO19\.vscode\extensions\spades.vs-picgo-2.1.6\dist\extension.js:94523:21)
> 	at Object.module.exports [as default] (c:\Users\MAO19\.vscode\extensions\spades.vs-picgo-2.1.6\dist\extension.js:94542:13)
> 	at new DB (c:\Users\MAO19\.vscode\extensions\spades.vs-picgo-2.1.6\dist\extension.js:106155:34)
> 	at PicGo.initConfig (c:\Users\MAO19\.vscode\extensions\spades.vs-picgo-2.1.6\dist\extension.js:103330:19)
> 	at new PicGo (c:\Users\MAO19\.vscode\extensions\spades.vs-picgo-2.1.6\dist\extension.js:103309:14)
> 	at Object.51683 (c:\Users\MAO19\.vscode\extensions\spades.vs-picgo-2.1.6\dist\extension.js:170332:17)
> 	at __webpack_require__ (c:\Users\MAO19\.vscode\extensions\spades.vs-picgo-2.1.6\dist\extension.js:184620:42)
> 	at Object.50112 (c:\Users\MAO19\.vscode\extensions\spades.vs-picgo-2.1.6\dist\extension.js:169847:36)
> 	at __webpack_require__ (c:\Users\MAO19\.vscode\extensions\spades.vs-picgo-2.1.6\dist\extension.js:184620:42)
> 	at c:\Users\MAO19\.vscode\extensions\spades.vs-picgo-2.1.6\dist\extension.js:184674:18
> 	at Object.<anonymous> (c:\Users\MAO19\.vscode\extensions\spades.vs-picgo-2.1.6\dist\extension.js:184675:12)
> ```

- -啊，好像是我的config.json格式不对，删除后自动生成，问题就解决了
