### ISSUE TITLE
[咨询] 请问vs-picgo 支持 picgo的插件吗 ?

### ISSUE THREAD

**Issue by HuangDongdong666** [PicGo/vs-picgo#128]
指定 configPath 为原本桌面端的data.json ,调用picgo的插件,
一直提示 "You must be logged in to use" , 
同一个插件在桌面端可以用,有什么处理办法吗?

桌面端 : Windows 2.3.0
vs-picgo : 2.1.6
插件 : gitea 1.1.1

**Comment by 2ipm1nd** [comment]
我也有相同的問題，無法使用自定義webupload來上傳圖片，有點麻煩……

```
2022-07-19 17:44:58 [PicGo INFO] Before transform 
2022-07-19 17:44:58 [PicGo INFO] Transforming... Current transformer is [path] 
2022-07-19 17:44:58 [PicGo INFO] Before upload 
2022-07-19 17:44:58 [PicGo INFO] beforeUploadPlugins: vsPicgoRenamePlugin running 
2022-07-19 17:44:58 [PicGo WARN] Can't find uploader - smms, switch to default uploader - smms 
2022-07-19 17:44:58 [PicGo INFO] Uploading... Current uploader is [smms] 
2022-07-19 17:44:59 [PicGo WARN] failed 
2022-07-19 17:44:59 [PicGo ERROR] 
------Error Stack Begin------
Error: You must be logged in to use.
	at Object.handle (c:\Users\PC425\.vscode\extensions\spades.vs-picgo-2.1.6\dist\extension.js:105328:23)
	at processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async Lifecycle.doUpload (c:\Users\PC425\.vscode\extensions\spades.vs-picgo-2.1.6\dist\extension.js:103195:9)
	at async Lifecycle.start (c:\Users\PC425\.vscode\extensions\spades.vs-picgo-2.1.6\dist\extension.js:103141:13)
	at async PicGo.upload (c:\Users\PC425\.vscode\extensions\spades.vs-picgo-2.1.6\dist\extension.js:103451:32)
-------Error Stack End------- 
```
看了`log`檔，好像是沒辦法使用插件上傳……，所以跑到默認的smms圖床了

**Comment by C0DECHEF** [comment]
@2ipm1nd 对的，我遇到了这个问题，通过 picgo-cli 可以使用自己编写的插件上传图片。但是在 vscode picgo 插件里面不行，看了 picgo-core 的日志，提示跟你一样

> Can't find uploader - smms, switch to default uploader - smms

@upupming 应该是一个 BUG 😭

**Comment by C0DECHEF** [comment]
@upupming 这个什么时候可以解决呀，2023 了 😭

**Comment by C0DECHEF** [comment]
> @upupming 这个什么时候可以解决呀，2023 了 😭

@Spades-S @Molunerfinn

**Comment by flynncao** [comment]
Linux用户可以试试这个版本的VSC extension，我用着可以正常上传 （Ubuntu24) 

https://marketplace.visualstudio.com/items?itemName=whyreal.wr-vs-picgo

**Comment by 2ipm1nd** [comment]
改用 piclist了，一切正常
